/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_orang2;

/**
 *
 * @author Ola
 */
import Canvas.MyCanvasPanel;
import gui_orang2.Properties;

public class ReplayFrame extends javax.swing.JFrame {
    Properties Properties;
    int joint1Begin;
    int joint2Begin;
    int joint3Begin;
    int joint4Begin;
    int joint5Begin; 
    int joint6Begin;
    int joint1End;
    int joint2End;
    int joint3End;
    int joint4End;
    int joint5End;
    int joint6End;

    /**
     * Creates new form ReplayFrame
     */
    public ReplayFrame(Properties props,int joint1Begin, int joint2Begin, int joint3Begin, int joint4Begin, int joint5Begin, int joint6Begin, int joint1End, int joint2End, int joint3End, int joint4End, int joint5End, int joint6End) {
        Properties = props;
        this.joint1Begin = joint1Begin;
        this.joint2Begin = joint2Begin;
        this.joint3Begin= joint3Begin;
        this.joint4Begin= joint4Begin;
        this.joint5Begin= joint5Begin; 
        this.joint6Begin= joint6Begin;
        this.joint1End= joint1End;
        this.joint2End= joint2End;
        this.joint3End= joint3End;
        this.joint4End= joint4End;
        this.joint5End= joint5End;
        this.joint6End= joint6End;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myCanvasPanel1 = new Canvas.MyCanvasPanel(Properties, joint1Begin, joint2Begin, joint3Begin, joint4Begin, joint5Begin, joint6Begin, joint1End, joint2End, joint3End, joint4End, joint5End, joint6End);
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout myCanvasPanel1Layout = new javax.swing.GroupLayout(myCanvasPanel1);
        myCanvasPanel1.setLayout(myCanvasPanel1Layout);
        myCanvasPanel1Layout.setHorizontalGroup(
            myCanvasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        myCanvasPanel1Layout.setVerticalGroup(
            myCanvasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jButton1.setText("Replay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(myCanvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(myCanvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       myCanvasPanel1.runSim(joint1End, joint2End, joint3End, joint4End, joint5End, joint6End);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReplayFrame(props).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private Canvas.MyCanvasPanel myCanvasPanel1;
    // End of variables declaration//GEN-END:variables
}
